all:
	clear
	gcc -Wall -o P1 Template.c
	gcc -Wall -o P2 Template.c
	gcc -Wall -o P3 Template.c
	gcc -Wall -o P4 Template.c
	gcc -Wall -o P5 Template.c
	gcc -Wall -o P6 Template.c
	gcc -Wall -o P7 Template.c
	gcc -Wall -o P8 Template.c
	gcc -Wall -o P9 Template.c
	gcc -Wall -o P10 Template.c
	gcc -Wall -o P11 Template.c
	gcc -Wall -o P12 Template.c
	gcc -Wall -o P13 Template.c
	gcc -Wall -o P14 Template.c
	gcc -Wall -o P15 Template.c
	gcc -Wall -o P16 Template.c
	gcc -Wall -o P17 Template.c
	gcc -Wall -o P18 Template.c
	gcc -Wall -o P19 Template.c
	gcc -Wall -o P20 Template.c