all:
	clear
	gcc -Wall -o interpretador interpretador.c
	gcc -Wall -o escalonador queue.c escalonador.c 
	./interpretador 
programs:
	clear
	gcc -Wall -o P1 Template.c
	gcc -Wall -o P2 Template.c
	gcc -Wall -o P3 Template.c
	gcc -Wall -o P4 Template.c
	gcc -Wall -o P5 Template.c